/**
 * 离线自检：解析器 / 打包器 / 元数据探测
 * 用法：node scripts/selftest.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { extractPage, extractCss } from '../server/extract.mjs';
import { ZipWriter } from '../server/zip.mjs';
import { imageDimensions, mediaMeta, detectSignature, looksTextual } from '../server/probe.mjs';
import { classify, extFromPath, typeFromExt } from '../server/mime.mjs';
import { preFilter, postFilter, contentSignal, summarize, trimFiltered, MAX_FILTERED_DETAIL } from '../server/policy.mjs';
import { urlMeta, declaredEdge } from '../server/urlmeta.mjs';
import { pdfMeta, officeMeta, playlistMeta } from '../server/docmeta.mjs';
import { fontMeta } from '../server/probe.mjs';
import { normalizeUrl } from '../server/net.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const BASE = 'http://127.0.0.1:4620/samples/lab';
const html = fs.readFileSync(path.join(ROOT, 'public/samples/lab.html'), 'utf-8');

let pass = 0;
let fail = 0;
const ok = (cond, label, detail) => {
  if (cond) { pass++; console.log('  \u001b[32mPASS\u001b[0m ' + label); }
  else { fail++; console.log('  \u001b[31mFAIL\u001b[0m ' + label + (detail ? '  \u001b[2m' + detail + '\u001b[0m' : '')); }
};

console.log('\n\u001b[1m1. HTML 解析器\u001b[0m');
const t0 = Date.now();
const r = extractPage(html, BASE);
const ms = Date.now() - t0;
ok(ms < 1500, '解析耗时 ' + ms + 'ms（< 1500ms）', ms + 'ms');
const urls = r.resources.map((x) => x.url);
const has = (frag) => urls.some((u) => u.includes(frag));
ok(has('aurora-1920x1080.png'), '抓到 img src 图片');
ok(has('badge-96.png') && has('badge-512.png'), '抓到 srcset 多密度候选');
ok(has('icon-mask.svg'), '抓到 SVG 矢量');
ok(has('blip-mono.wav') && has('chime-stereo.wav'), '抓到 video source / audio src');
ok(has('specimen.pdf') && has('bundle-sample.zip') && has('inventory.csv'), '抓到 a[download] 文档与压缩包');
ok(has('missing-404.png'), '抓到失效引用（不静默丢弃）');
ok(has('hidden-lazy-320x200.png'), '抓到仅存在于脚本 JSON 的隐藏地址');
ok(has('dot-64.png') && r.resources.some((x) => x.attr === 'link:href' || x.tag === 'link'), '抓到 favicon link');
ok(r.resources.some((x) => x.url.includes('aurora-1920x1080') && x.count >= 3), '同一图片被 img/style/script 三处引用并合并计数');
ok(r.resources.filter((x) => x.provenance === 'datauri').length === 2, '抓到 2 个 data URI 图片（含 35KB 大图）');
ok(r.resources.some((x) => x.url.includes('aurora-2560x1440') && x.count >= 2), '抓到懒加载 data-src（与 og:image 合并）');
ok(r.resources.some((x) => x.provenance === 'inferred' && x.url.includes('hidden-lazy')), '脚本内嵌裸链接标记为 inferred');
ok(!!r.doc.favicon && r.doc.favicon.includes('dot-64'), '读取 favicon 元数据');
ok(!!r.doc.ogImage && r.doc.ogImage.includes('aurora-2560'), '读取 og:image');
ok(/资源标本馆/.test(r.doc.title), '读取 title：' + r.doc.title);
ok(r.textBlocks.length > 12, '文案块数量 ' + r.textBlocks.length);
ok(r.textBlocks.some((b) => b.tag === 'h1' && /资源标本馆/.test(b.text)), '标题层级 h1');
ok(r.textBlocks.filter((b) => b.level >= 2).length >= 6, '二级以上标题 >= 6');
ok(r.textBlocks.some((b) => b.tag === 'blockquote'), '引用块');
ok(r.textBlocks.some((b) => b.tag === 'td'), '表格单元格文案');
ok(r.textBlocks.some((b) => b.zone === 'noise'), '页脚文字被标记为 noise');
ok(extFromPath('a/b/image.png') === 'png' && extFromPath('archive.tar.gz') === 'gz' && extFromPath('noext') === '', '扩展名解析');
const mainPara = r.textBlocks.find((b) => b.tag === 'p' && b.chars > 80);
ok(!!mainPara, '存在长正文段落（chars=' + (mainPara ? mainPara.chars : 0) + '）');
ok(r.keywords.length > 4, '关键词抽取 ' + r.keywords.length + ' 条：' + r.keywords.slice(0, 5).map((k) => k.term).join('/'));
const dupIds = new Set(r.resources.filter((x) => x.url).map((x) => x.url));
const httpRefs = r.resources.filter((x) => x.url).length;
ok(dupIds.size === httpRefs, '按绝对 URL 去重（http ' + httpRefs + ' 条 + ' + (r.resources.length - httpRefs) + ' 个内联）');
ok(r.resources.every((x) => !/^(javascript|mailto):/i.test(x.url)), '过滤非 http 协议');
ok(r.resources.some((x) => x.count > 1), '重复引用计数 count>1');
const classified = r.resources.filter((x) => x.type === 'other' && typeFromExt(x.ext));
ok(classified.length === 0, '扩展名与类别一致', classified.map((x) => x.ext).join(','));

console.log('\n\u001b[1m2. 分类与 URL\u001b[0m');
ok(classify({ mime: '', ext: 'webp', context: '' }) === 'image', 'webp → image');
ok(classify({ mime: '', ext: 'm4a', context: '<video' }) === 'audio', 'm4a → audio');
ok(classify({ mime: 'application/octet-stream', ext: 'woff2', context: '' }) === 'font', 'woff2 → font');
ok(classify({ mime: '', ext: 'svg', context: '<img' }) === 'vector', 'svg → vector');
ok(classify({ mime: 'image/png', ext: '', context: '' }) === 'image', '仅 MIME 也能定类');
ok(normalizeUrl('../a.png', BASE) === 'http://127.0.0.1:4620/a.png', '相对路径 ../ 解析');
ok(normalizeUrl('assets/x.png', BASE) === 'http://127.0.0.1:4620/samples/assets/x.png', '相对路径 assets/ 解析');
ok(normalizeUrl('//cdn.x.com/a.png', BASE) === 'https://cdn.x.com/a.png' || normalizeUrl('//cdn.x.com/a.png', BASE) === 'http://cdn.x.com/a.png', '协议相对地址');
ok(normalizeUrl('javascript:void(0)', BASE) === null, '拒绝 javascript: 伪地址');
ok(normalizeUrl('assets/a.png?v=1#x', BASE).indexOf('#') < 0, '去掉 hash');

console.log('\n\u001b[1m3. 元数据探测\u001b[0m');
const png = fs.readFileSync(path.join(ROOT, 'public/samples/assets/aurora-1920x1080.png'));
const dims = imageDimensions(png, 'image/png');
ok(dims && dims.width === 1920 && dims.height === 1080, 'PNG 尺寸 1920x1080', JSON.stringify(dims));
const small = png.subarray(0, 64);
ok(imageDimensions(small, 'image/png').width === 1920, '仅前 64 字节即可读出 PNG 尺寸');
const svgBuf = fs.readFileSync(path.join(ROOT, 'public/samples/assets/logo-crest.svg'));
const sv = imageDimensions(svgBuf, 'image/svg+xml');
ok(sv && sv.width === 320 && sv.height === 120, 'SVG viewBox/width 解析', JSON.stringify(sv));
const wavBuf = fs.readFileSync(path.join(ROOT, 'public/samples/assets/chime-stereo.wav'));
const wm = mediaMeta(wavBuf, 'audio/wav', 'x.wav');
ok(wm.duration > 5.4 && wm.duration < 5.6 && wm.channels === 2 && wm.sampleRate === 44100, 'WAV 时长/声道/采样率 ' + JSON.stringify(wm));
const sigP = detectSignature(png);
ok(sigP && sigP.ext === 'png', '魔数识别 PNG');
const sigW = detectSignature(wavBuf);
ok(sigW && sigW.type === 'audio', '魔数识别 WAV');
ok(detectSignature(fs.readFileSync(path.join(ROOT, 'public/samples/assets/specimen.pdf'))).ext === 'pdf', '魔数识别 PDF');
ok(detectSignature(fs.readFileSync(path.join(ROOT, 'public/samples/assets/bundle-sample.zip'))).ext === 'zip', '魔数识别 ZIP');
ok(looksTextual(Buffer.from('hello \u4f60好')) === true, '文本判定');
ok(looksTextual(Buffer.from([0, 1, 2, 3, 0, 0, 255, 9])) === false, '二进制判定');

console.log('\n\u001b[1m4. ZIP 打包器\u001b[0m');
const { Writable } = await import('node:stream');
const chunks = [];
const sink = new Writable({ write(c, e, cb) { chunks.push(Buffer.from(c)); cb(); } });
const zip = new ZipWriter(sink);
const payload = Buffer.concat(Array.from({ length: 400 }, () => Buffer.from('IDENTIFY 原始字节导出测试 ')));
await zip.add('包 A/图片/中文名称.png', png);
await zip.add('包 A/README.txt', 'hello');
await zip.add('包 A/大文件.bin', payload);
await zip.finish();
const zipBuf = Buffer.concat(chunks);
fs.writeFileSync(path.join(ROOT, '.tmp-selftest.zip'), zipBuf);
ok(zipBuf.readUInt32LE(0) === 0x04034b50, '本地文件头签名');
ok(zipBuf.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06])) > 0, '中央目录结束记录');
const roundtrip = await unzipCheck(zipBuf);
ok(roundtrip.ok, '解压往返一致：条目 ' + roundtrip.names.join(' , '), roundtrip.error || '');
ok(roundtrip.samePng, 'PNG 字节完全一致（原大小 / 未再编码）');
ok(roundtrip.sameBig, 'deflate 往返一致');
fs.rmSync(path.join(ROOT, '.tmp-selftest.zip'), { force: true });

function unzipCheck(buf) {
  const result = { ok: false, names: [], samePng: false, sameBig: false, error: '' };
  try {
    const eocd = buf.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
    const count = buf.readUInt16LE(eocd + 10);
    let p = buf.readUInt32LE(eocd + 16);
    for (let i = 0; i < count; i++) {
      if (buf.readUInt32LE(p) !== 0x02014b50) throw new Error('central header 损坏 @' + p);
      const method = buf.readUInt16LE(p + 10);
      const usize = buf.readUInt32LE(p + 24);
      const nameLen = buf.readUInt16LE(p + 28);
      const extraLen = buf.readUInt16LE(p + 30);
      const commentLen = buf.readUInt16LE(p + 32);
      const lho = buf.readUInt32LE(p + 42);
      const name = buf.subarray(p + 46, p + 46 + nameLen).toString('utf-8');
      result.names.push(name);
      const lNameLen = buf.readUInt16LE(lho + 26);
      const lExtraLen = buf.readUInt16LE(lho + 28);
      const csize = buf.readUInt32LE(lho + 18);
      const dataStart = lho + 30 + lNameLen + lExtraLen;
      const data = buf.subarray(dataStart, dataStart + csize);
      const out = method === 8 ? zlib.inflateRawSync(data) : data;
      if (out.length !== usize) throw new Error(name + ' 体积不符 ' + out.length + '!=' + usize);
      if (name.endsWith('.png')) result.samePng = out.equals(png);
      if (name.endsWith('.bin')) result.sameBig = out.equals(payload);
      p += 46 + nameLen + extraLen + commentLen;
    }
    result.ok = true;
  } catch (err) { result.error = err.message; }
  return result;
}


/* ================================================= ====== 新增章节 ====== */

console.log('\n\u001b[1m5. 扫描策略（UI 图标 / 字体 / 样式表 / 脚本 / 数据不扫描）\u001b[0m');
const ref = (o) => Object.assign({ url: 'https://site.com/a/b.png', type: 'image', tag: 'img', attr: 'src', provenance: 'attr' }, o || {});
ok(preFilter(ref({ type: 'font' })) !== null, '字体在解析阶段排除（零请求）');
ok(preFilter(ref({ type: 'stylesheet' })) !== null, '样式表排除（但仍会被读取）');
ok(preFilter(ref({ type: 'script' })) !== null, '脚本 / source map / wasm 排除');
ok(preFilter(ref({ type: 'data' })) !== null, 'JSON / XML / manifest 排除');
ok(preFilter(ref({ type: 'icon' })) !== null, 'UI 图标类别排除');
ok(preFilter(ref({ type: 'icon' }), { includeIcons: true }) === null, '打开「UI 图标」开关后保留');
ok(preFilter(ref({ type: 'font' }), { includeTech: true }) === null, '打开「技术资源」开关后保留');
ok(preFilter(ref({ tag: 'link', attr: 'rel:href', url: 'https://site.com/favicon.ico', type: 'icon' })) !== null, 'favicon 排除');
ok(preFilter(ref({ url: 'https://site.com/images/icons/apple-touch-icon.png' })) !== null, '图标目录 + 图标文件名排除');
ok(preFilter(ref({ url: 'https://site.com/assets/spacer.gif' })) !== null, 'spacer 占位图排除');
ok(preFilter(ref({ url: 'https://site.com/1x1.png' })) !== null, '1×1 命名排除');
ok(preFilter(ref({ url: 'https://site.com/beacon.php?u=1' })) !== null, '统计打点地址排除');
ok(preFilter(ref({ url: 'https://www.google-analytics.com/ga.js' })) !== null, '打点域名排除');
ok(preFilter(ref({ url: 'https://images.unsplash.com/photo-1500?w=24&h=24' })) !== null, '图片服务声明 24px → 判定为图标');
ok(preFilter(ref({ url: 'https://images.unsplash.com/photo-1500?w=1600&q=80' })) === null, '声明 1600px 的内容图保留');
ok(preFilter(ref({ url: 'https://site.com/blog/hero-1920x1080.jpg' })) === null, '正文大图保留');
ok(preFilter(ref({ type: 'other', url: 'https://site.com/api/media?id=42', provenance: 'css' })) === null, '无扩展名的 CSS 引用先探测再判');
ok(preFilter(ref({ type: 'other', tag: 'a', attr: 'href', provenance: 'link', url: 'https://site.com/portal?a=1' })) !== null, '毫无内容线索的 other 排除');
ok(preFilter(ref({ type: 'other', url: 'https://site.com/media?id=7' })) === null, '<img> 指向无扩展名地址 → 先探测');
ok(preFilter(ref({ cssProp: 'mask-image', url: 'https://site.com/decor.png' })) !== null, 'CSS mask 图片判定为界面装饰');
ok(preFilter(ref({ cssProp: 'list-style-image', url: 'https://site.com/bullet.png' })) !== null, '列表符号图片排除');
ok(preFilter(ref({ sprite: true, url: 'https://site.com/strip.png' })) !== null, 'background-position 偏移 → 雪碧图排除');
ok(preFilter(ref({ sprite: true, declaredWidth: 1200, url: 'https://site.com/big.png' })) === null, '声明 1200px 的雪碧图写法不误杀');
ok(preFilter(ref({ selector: '.site-header__logo img', url: 'https://site.com/x.png' })) !== null, '选择器含 logo → 界面装饰');
ok(preFilter(ref({ dataUri: { mime: 'image/gif', approxBytes: 120, data: 'R0lG' } })) !== null, '极小内联数据排除');
ok(postFilter({ type: 'image', width: 32, height: 32 }).reason === 'icon', '真实 32×32 → 图标');
ok(postFilter({ type: 'image', width: 1, height: 1 }).reason === 'pixel', '真实 1×1 → 占位像素');
ok(postFilter({ type: 'image', width: 1200, height: 800 }) === null, '真实 1200×800 → 保留');
ok(postFilter({ type: 'vector', sprite: true, symbols: 12 }) !== null, 'SVG 精灵图排除');
ok(postFilter({ type: 'vector', glyphLike: true, width: 24, height: 24, shapes: 2 }) !== null, '图标字形 SVG 排除');
ok(postFilter({ type: 'font' }) !== null && postFilter({ type: 'font' }, { includeTech: true }) === null, 'postFilter 二次确认技术资源');
ok(postFilter({ type: 'other', mime: 'image/png', width: 800, height: 600 }) === null, 'other 但魔数是图片 → 保留');
ok(postFilter({ type: 'icon', iconSet: true, sizes: '16×16, 32×32, 128×128' }).reason === 'icon', '多尺寸图标集排除');
ok(postFilter({ type: 'image', iconSet: true, entries: 6, sizes: '16×16 / 32×32' }).reason === 'icon', 'ICO 多尺寸（字符串 sizes）排除');
const trim = trimFiltered(Array.from({ length: 620 }, (x, i) => ({ reason: 'font', url: 'f' + i })));
ok(trim.kept.length === MAX_FILTERED_DETAIL && trim.dropped === 220, '排除明细按理由限量（' + trim.kept.length + ' + ' + trim.dropped + '）');
ok(summarize([{ reason: 'font' }, { reason: 'font' }, { reason: 'icon' }]).total === 3, '排除摘要计数');
ok(contentSignal(ref({ provenance: 'css' })) !== '', '内容线索：样式表引用');
ok(contentSignal(ref({ tag: 'video', attr: 'src', url: 'https://site.com/stream?id=9' })) !== '', '内容线索：媒体标签');
ok(contentSignal(ref({ url: 'https://site.com/x?w=800' })) !== '', '内容线索：图片处理参数');
const layerCss = extractCss(fs.readFileSync(path.join(ROOT, 'public/samples/assets/layer-2.css'), 'utf-8'), 'http://127.0.0.1:4620/samples/assets/layer-2.css');
const stripRef = layerCss.find((x) => /ui-strip/.test(x.url));
ok(!!stripRef && stripRef.sprite === true, '样式表雪碧图定位 → sprite 标记', JSON.stringify(stripRef && stripRef.sprite));
const featureRef = layerCss.find((x) => /feature-image-no-extension/.test(x.url));
ok(!!featureRef && featureRef.type === 'other' && preFilter(featureRef) === null, '样式表里的无扩展名图先探测再判');
ok(layerCss.filter((x) => x.provenance === 'css' && !x.cssProp).length === 0, 'CSS 引用的属性名全部解析');
const manifestRef = r.resources.find((x) => /site\.webmanifest/.test(x.url));
ok(!!manifestRef && preFilter(manifestRef) !== null, 'webmanifest 归入不扫描类别');

console.log('\n\u001b[1m6. 地址语义（图片服务 / CDN 参数）\u001b[0m');
const um = (u) => urlMeta(u);
ok(um('https://images.unsplash.com/photo-1?w=1600&q=80').width === 1600, 'unsplash w 参数');
ok(um('https://images.unsplash.com/photo-1?w=1600').square === 1, '只有宽时标记为见方而非臆造高');
ok(um('https://lh3.googleusercontent.com/x=s2000-c').width === 2000, 'googleusercontent =s 尺寸');
ok(um('https://a.com/_next/image?url=%2Fhero%2Fphoto.jpg&w=1200').inner.indexOf('photo.jpg') > 0, 'Next 优化器还原内层地址');
ok(um('https://res.cloudinary.com/d/image/upload/w_800,h_600/x.jpg').width === 800, 'Cloudinary w_/h_ 变换串');
ok(um('https://cdn.example.com/a.jpg?x-oss-process=image/resize,w_900').width === 900, '任意域名的 x-oss-process');
ok(um('https://cbu01.alicdn.com/img/x.jpg_400x400q90.jpg').width === 400, '阿里 / 淘宝尺寸后缀');
ok(um('https://example.com/cdn-cgi/image/width=1200/https://o.com/a.jpg').width === 1200, 'Cloudflare image-transform');
ok(um('https://p.com/x.jpg@900w_1e_1c').width === 900, '火山 / 短视频 900w 写法');
ok(um('https://live.staticflickr.com/1/ab_cd_b.jpg').width === 1024, 'Flickr _b 尺寸码');
ok(um('https://i.ytimg.com/vi/abc/maxresdefault.jpg').width === 1280, 'YouTube 缩略图尺寸');
ok(um('https://pbs.twimg.com/media/X.jpg:large').width === 1200, 'Twitter :large');
ok(um('https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/B.png/800px-B.png').width === 800, 'Wikimedia 800px-');
ok(um('https://cdn.shopify.com/s/files/1/2/x.jpg?v=1&width=1400').width === 1400, 'Shopify width 参数优先于数字目录段');
ok(!um('https://cdn.shopify.com/s/files/1/2/x.jpg?v=1').width, 'ID 路径不再被当成尺寸');
ok(um('https://www.gravatar.com/avatar/0?s=80&d=mm').avatar === 1, 'Gravatar 默认头像标记');
ok(um('https://img.example.com/photos/hero-1920x1080.jpg').height === 1080, '文件名里的 1920x1080');
ok(um('https://img.example.com/p@2x.png').dpr === 2, '@2x 密度');
ok(um('https://example.com/icon-24x24.svg').width === 24, 'SVG 声明尺寸');
ok(declaredEdge(um('https://images.unsplash.com/photo-1?w=1600')) === 1600, 'declaredEdge 取最长边');
const badges = um('https://img.shields.io/badge/build-passing-green');
ok(badges.badge === 1 || /shields/i.test(badges.provider || ''), '徽章服务识别');

console.log('\n\u001b[1m7. 容器与文档深度解析\u001b[0m');
const asset = (n) => fs.readFileSync(path.join(ROOT, 'public/samples/assets', n));
const g1 = imageDimensions(asset('spacer.gif'), 'image/gif');
ok(g1.width === 1 && g1.height === 1 && g1.frames === 1, 'GIF 1×1 · 帧数', JSON.stringify(g1));
const pngStrip = imageDimensions(asset('ui-strip.png'), 'image/png');
ok(pngStrip.width === 48 && pngStrip.height === 144, 'PNG 精灵尺寸 48×144');
const glyphSvg = imageDimensions(asset('icons/ui-check-16x16.svg'), 'image/svg+xml');
ok(glyphSvg.glyphLike === true && glyphSvg.width === 16, 'SVG 图标字形判定', JSON.stringify(glyphSvg));
const crestSvg = imageDimensions(asset('logo-crest.svg'), 'image/svg+xml');
ok(crestSvg.glyphLike !== true && crestSvg.textNodes > 0, '带文字的 SVG 不是图标');
const sigNoExt = detectSignature(asset('feature-image-no-extension'));
ok(sigNoExt && sigNoExt.ext === 'png', '无扩展名文件按魔数定为 PNG');
const noExtDims = imageDimensions(asset('feature-image-no-extension'), 'application/octet-stream');
ok(noExtDims.width === 640 && noExtDims.height === 400, '无扩展名文件仍读出 640×400');
const rp = pdfMeta(asset('report.pdf'));
ok(rp.pages === 2 && rp.width === 595 && rp.height === 842, 'PDF 页数与页面尺寸', JSON.stringify(rp).slice(0, 90));
ok(/资源识别报告/.test(rp.title || '') && /DeepSeek/.test(rp.creator || ''), 'PDF 信息字典（UTF-16BE 十六进制串）', JSON.stringify([rp.title, rp.creator]));
ok(/年初|2024-05-01/.test(rp.created || '') && rp.producer === 'IDENTIFY 样本馆打印驱动', 'PDF 日期与生产者', rp.created + ' / ' + rp.producer);
const hls = playlistMeta(asset('master.m3u8'), 'master.m3u8', 'application/vnd.apple.mpegurl');
ok(hls.variantCount === 4 && hls.width === 1920 && !hls.live, 'HLS 主清单 4 档且非直播', JSON.stringify(hls).slice(0, 120));
ok(hls.subtitleTracks === 1 && hls.audioGroups === 1 && hls.languages.indexOf('zh') >= 0, 'HLS 字幕 / 音频组 / 语言');
const media = playlistMeta(asset('1080p-index.m3u8'), 'i.m3u8', '');
ok(media.segments === 3 && media.duration === 15 && media.startSequence === 10482 && !media.live, 'HLS 分片清单时长与序号', JSON.stringify(media));
const dash = playlistMeta(asset('master.mpd'), 'master.mpd', 'application/dash+xml');
ok(dash.duration === 96.5 && dash.adaptive && dash.variantCount === 4, 'DASH 时长与自适应档位', JSON.stringify(dash).slice(0, 90));
const mp3 = mediaMeta(asset('tagged.mp3'), 'audio/mpeg', 'tagged.mp3');
ok(mp3.title === 'Original Size' && mp3.creator === 'IDENTIFY Sampler' && mp3.album === 'Byte Fidelity', 'ID3v2 标题 / 艺人 / 专辑', JSON.stringify(mp3).slice(0, 120));
ok(mp3.genre === 'Rock' && mp3.year === '2024' && mp3.sampleRate === 44100 && mp3.bitrate === 128000, 'ID3 流派年份 + MPEG 帧头码率', JSON.stringify([mp3.genre, mp3.year, mp3.sampleRate, mp3.bitrate]));
ok(mp3.duration > 0.6 && mp3.duration < 0.75, 'MP3 时长（TLEN / 帧计数）', String(mp3.duration));
const font = fontMeta(asset('icon-glyphs.ttf'), 'font/ttf');
ok(font.glyphs === 64 && font.unitsPerEm === 1000 && font.weightClass === 600, 'TTF 表目录 / 字形数 / 字重', JSON.stringify(font).slice(0, 120));
ok(/Lab Icon Glyphs/.test(font.family || '') && /Semibold/.test(font.style || ''), 'TTF name 表家族与样式', font.family + ' / ' + font.style);
ok(font.iconFont === true && /SIL/.test(font.license || ''), '图标字体判定与授权信息');
const zmeta = officeMeta(asset('bundle-sample.zip'));
ok(zmeta.entries === 3 && zmeta.mediaFiles === 1, 'ZIP 中央目录统计', JSON.stringify(zmeta));
const labPages = extractPage(fs.readFileSync(path.join(ROOT, 'public/samples/base-path.html'), 'utf-8'), BASE);
ok(labPages.resources.some((x) => x.url === 'http://127.0.0.1:4620/samples/assets/badge-512.png'), '<base href> 参与相对地址解析', labPages.resources.map((x) => x.url).filter((x) => /badge/.test(x)).join(','));
ok(labPages.resources.some((x) => x.provenance === 'json' && /aurora-1920x1080/.test(x.url)), 'data-* 里的 JSON 地址被提取');
ok(!labPages.resources.some((x) => /\bw\b/.test(String(x.attr))), '不会被误判的属性名制造引用');
console.log('\n\u001b[1m8. WebP 动图与边角容器\u001b[0m');
const riffWebp = (chunks) => {
  const body = Buffer.concat([Buffer.from('WEBP', 'ascii'), ...chunks]);
  const head = Buffer.concat([Buffer.from('RIFF', 'ascii'), (() => { const x = Buffer.alloc(4); x.writeUInt32LE(body.length + 4, 0); return x; })()]);
  return Buffer.concat([head, body]);
};
const ck = (id, payload) => {
  const h = Buffer.concat([Buffer.from(id, 'ascii'), (() => { const x = Buffer.alloc(4); x.writeUInt32LE(payload.length, 0); return x; })()]);
  return payload.length % 2 ? Buffer.concat([h, payload, Buffer.from([0])]) : Buffer.concat([h, payload]);
};
const vp8x = Buffer.alloc(10);
vp8x[0] = 0x02;
vp8x[4] = 99; vp8x[5] = 0; vp8x[6] = 0;
vp8x[7] = 49; vp8x[8] = 0; vp8x[9] = 0;
const anim = Buffer.alloc(6);
anim.writeUInt16LE(3, 4);
const anmf = (ms, flags) => { const f = Buffer.alloc(16); f.writeUIntLE(ms, 12, 3); f[15] = flags || 0; return f; };
const webpBuf = riffWebp([ck('VP8X', vp8x), ck('ANIM', anim), ck('ANMF', anmf(120)), ck('ANMF', anmf(380)), ck('ANMF', anmf(500, 0x03))]);
const wInfo = imageDimensions(webpBuf, 'image/webp');
ok(wInfo.width === 100 && wInfo.height === 50, 'VP8X 画布尺寸 100×50', JSON.stringify(wInfo).slice(0, 80));
ok(wInfo.animated === true && wInfo.frames === 3 && wInfo.loops === '3 次', 'ANIM 循环次数', String(wInfo.loops));
ok(Math.abs(wInfo.duration - 10) < 0.001, 'ANMF 帧时长累加为 10 秒', String(wInfo.duration));
ok(wInfo.keyframes === 2 && wInfo.disposal === '每帧复位' && wInfo.overwrite === true, '关键帧计数 / 处置 / 覆盖方式', JSON.stringify([wInfo.keyframes, wInfo.disposal, wInfo.overwrite]));
const sigWebp = detectSignature(webpBuf);
ok(sigWebp && sigWebp.ext === 'webp', '动图 WebP 魔数识别', JSON.stringify(sigWebp));
console.log('\n\u001b[1m结果：' + pass + ' 通过 / ' + fail + ' 失败\u001b[0m\n');
process.exitCode = fail ? 1 : 0;